version: 1.2
workflows:
- name: vcf-to-zarr-trial-subset
  subclass: wdl
  primaryDescriptorPath: /vcf-to-zarr-trial-subset.wdl
- name: vcf-to-zarr-trial3
  subclass: wdl
  primaryDescriptorPath: /vcf-to-zarr-trial3.wdl
- name: 1000-3000-comparison
  subclass: wdl
  primaryDescriptorPath: /1000-3000-comparison.wdl
